spring:
  application:
    name: langchain4j
server:
  port: 8087
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-56e46db3b35443c2a0fc282db68a81c2
        model-name: qwen-plus
      embedding-model:
        api-key: sk-56e46db3b35443c2a0fc282db68a81c2
        model-name: text-embedding-v3
pgvector:
  database: ai
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456@Root
  table: my_embeddings

