spring:
  application:
    name: langchain4j
server:
  port: 8087
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-56e46db3b35443c2a0fc282db68a81c2
        model-name: deepseek-v3

